---
title: "EDA - MollyN"
execute: 
  echo: true      
code-fold: false  
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyverse)
```


```{r}
setwd("/Users/mnelso11/Documents/GitHub/project-team-awesomest/data")
BookIns2017 <- read_csv("Book-Ins FY2017.csv")
BookIns2018 <- read_csv("Book-Ins FY2018.csv")
BookIns2019 <- read_csv("Book-Ins FY2019.csv")
BookIns2020 <- read_csv("Book-Ins FY2020.csv")
BookIns2021 <- read_csv("Book-Ins FY2021.csv")
BookIns2022 <- read_csv("Book-Ins FY2022.csv")
BookIns2023 <- read_csv("Book-Ins FY2023.csv")
BookIns2024 <- read_csv("Book-Ins FY2024.csv")
```
```{r}
BookIns <- BookIns2017 |>
  full_join(BookIns2018) |>
  full_join(BookIns2019) |>
  full_join(BookIns2020) |>
  full_join(BookIns2021) |>
  full_join(BookIns2022) |>
  full_join(BookIns2023) |>
  full_join(BookIns2024) 
```

```{r}
# Visualizations On Book-Ins/Arrests Over Time

BookIns |>
  filter(Criminality %in% c("Total Arrests")) |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
  labs(title = "Total Arrests Over Time", x = "Year", y = "Number of Arrests")

BookIns |>
  filter(Criminality %in% c("Criminal Convictions")) |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
  labs(title = "Criminal Convictions Arrests Over Time", x = "Year", y = "Number of Arrests")
  
BookIns |>
  filter(Criminality %in% c("Pending Criminal Charges")) |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
  labs(title = "Pending Criminal Charges Arrests Over Time", x = "Year", y = "Number of Arrests")

BookIns |>
  filter(Criminality %in% c("No Known Criminal Charges or Convictions", "Other Immigration Violator")) |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
  labs(title = "Non-Criminal/Other Violation Arrests Over Time", x = "Year", y = "Number of Arrests")
```


```{r}
# Calling Datasets

setwd("/Users/mnelso11/Documents/GitHub/project-team-awesomest/data")
BookIns2017 <- read_csv("Book-Ins FY2017.csv")
BookIns2018 <- read_csv("Book-Ins FY2018.csv")
BookIns2019 <- read_csv("Book-Ins FY2019.csv")
BookIns2020 <- read_csv("Book-Ins FY2020.csv")
BookIns2021 <- read_csv("Book-Ins FY2021.csv")
BookIns2022 <- read_csv("Book-Ins FY2022.csv")
BookIns2023 <- read_csv("Book-Ins FY2023.csv")
BookIns2024 <- read_csv("Book-Ins FY2024.csv")
ICEBudget <- read_csv("ICE_Budget.csv")
```
```{r}
BookIns <- BookIns2017 |>
  full_join(BookIns2018) |>
  full_join(BookIns2019) |>
  full_join(BookIns2020) |>
  full_join(BookIns2021) |>
  full_join(BookIns2022) |>
  full_join(BookIns2023) |>
  full_join(BookIns2024) 

BookIns <- BookIns %>%
  mutate(Criminality = case_when(
    Criminality %in% c("Other Immigration Violator", "No Known Criminal Charges or Convictions") ~ 
      "Other Immigration Violator/No Known Criminal Charges or Convictions",
    TRUE ~ Criminality
  ))
```


```{r}
# Visualizations On Book-Ins/Arrests Over Time

BookIns |>
  filter(Criminality %in% c("Total Arrests")) |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
  labs(title = "Total Arrests Over Time", x = "Year", y = "Number of Arrests")
```

```{r}
BookIns |>
   filter(Criminality != "Total Arrests") |>
  ggplot(aes(x = Year, y = Arrests)) + 
  geom_line() + 
    facet_wrap(~ Criminality, ncol = 1) +
  labs(title = "Arrests Over Time by Criminality", x = "Year", y = "Number of Arrests")
```

```{r}
ICEBudget <- ICEBudget |>
  rename(Budget = 'Budget (in millions)')
```

```{r}
ggplot(ICEBudget, aes(x = Year, y = Budget)) +
  geom_line()
```

```{r}
BookIns |>
  full_join(ICEBudget, by = "Year") |>
  filter(Criminality == "Total Arrests") |>
  ggplot(aes(x = Budget, y = Arrests, color = factor(Year))) +
  geom_point(size = 3) +
  labs(title = "Total Arrests vs. ICE Budget by Year",
       x = "ICE Budget",
       y = "Total Arrests",
       color = "Year") +
  theme_minimal()
```

```{r}
BookIns |>
  full_join(ICEBudget) |>
  filter(Criminality %in% c("Total Arrests")) |>
  ggplot(aes(x = Budget, y = Arrests)) + 
  geom_line()
```

# RQ3: 2019 vs. 2024
```{r}
# Calling Datasets

setwd("/Users/mnelso11/Documents/GitHub/project-team-awesomest/data")
BookIns_2024 <- read_csv("ICE Initial Book-Ins by Arresting Agency and Month_ EOFY2024.csv")
```

```{r}
BookIns_2019 <- BookIns_2019 |>
  mutate(Year = "2019")

BookIns_2024 <- BookIns_2024 |>
  pivot_longer(
    cols = -Agency,          
    names_to = "Month",      
    values_to = "Count"      
  ) |>
  mutate(Year = "2024")

BookIns_Comp <- BookIns_2024 |>
  full_join(BookIns_2019)
```

```{r}
BookIns_Comp |> 
  filter(Month != "Total", Agency == "ICE") |>
  mutate(Month = factor(Month, levels = month_order)) |>
  ggplot(aes(x = Month, y = Count, fill = Agency)) +
  geom_col(position = "dodge") +
  facet_wrap(~ Year) +
  labs(title = "Agency Book-Ins by Month",
       x = "Month",
       y = "Count") +
  theme_minimal()

BookIns_Comp |> 
  filter(Month != "Total") |>
  mutate(Month = factor(Month, levels = month_order)) |>
  ggplot(aes(x = Month, y = Count, fill = Agency)) +
  geom_col(position = "dodge") +
  facet_wrap(~ Year) +
  labs(title = "Agency Book-Ins by Month",
       x = "Month",
       y = "Count") +
  theme_minimal()
```

